# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8abc89a1225a260e79c2a41da504c2aa185b1fccee0d52f8c8bd85eacb14e63d45a77ded65764414cb857d4f71fc4b07141dcd7801caa11c6d3a771e2464e0d1

test:
  secret_key_base: 853d878d4da77f59d5d59803732fa9d9828c609948aad1a4ead63d3c7fdcfd2588644b02b96e446c89e34ce993027db5b4633019f3017f6af1c62e66534cad4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
